# Generated by Django 5.1.3 on 2024-11-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='illustration',
            new_name='contenu',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='souscategorie',
            name='description',
        ),
    ]
