# Generated by Django 5.1.3 on 2024-11-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_modele_produit_sujet_typerecherche_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contenu',
            new_name='background_image',
        ),
    ]
