# Generated by Django 5.1.3 on 2024-11-12 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_rename_contenu_article_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mot_cle_principal',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
