# Generated by Django 5.1.3 on 2024-11-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_article_mot_cle_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='recherche',
            name='modeles',
        ),
        migrations.AlterField(
            model_name='recherche',
            name='sujets',
            field=models.ManyToManyField(blank=True, related_name='recherches_sujet', to='Articles.sujet'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='types_recherche',
            field=models.ManyToManyField(blank=True, related_name='recherches_type', to='Articles.typerecherche'),
        ),
        migrations.AddField(
            model_name='recherche',
            name='models',
            field=models.ManyToManyField(blank=True, related_name='recherches_model', to='Articles.model'),
        ),
        migrations.DeleteModel(
            name='Modele',
        ),
    ]
