# Generated by Django 5.1.3 on 2024-11-12 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0009_alter_article_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recherche',
            name='date_recherche',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
