# Generated by Django 5.1.3 on 2024-11-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0010_recherche_date_recherche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_article',
            field=models.CharField(choices=[('produit', 'Produit'), ('recherche', 'Recherche'), ('stories', 'Stories'), ('affaires', 'Affaires Globales'), ('info', "Information sur l'Entreprise"), ('securite', 'Sécurité')], max_length=50),
        ),
    ]
