# Generated by Django 5.1.3 on 2024-11-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0011_alter_article_type_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_bussiness',
            field=models.BooleanField(default=False),
        ),
    ]
